# docker-compose.yml
version: '3'

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
      

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_API_URL=http://server:8080
    networks:
      - app-network


  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network


networks:
  app-network:

volumes:
  db_data:
